FIND_PATH(CLANG_STD_INCLUDE_DIR
  NAMES unordered_map
  PATH_SUFFIXES include/c++ include/c++/v1
  PATHS "${PROJECT_SOURCE_DIR}/../libc++/"
  ${CLANG_STD_ROOT}
  $ENV{CLANG_STD_ROOT}
  /usr/local/
  /usr/
)

message("Found clang stdandard library at: ${CLANG_STD_INCLUDE_DIR}.")

IF(CLANG_STD_INCLUDE_DIR)
  SET(CLANG_STD_FOUND TRUE)
ELSE(CLANG_STD_INCLUDE_DIR)
  SET(CLANG_STD_FOUND FALSE)
ENDIF(CLANG_STD_INCLUDE_DIR)

IF(CLANG_STD_FOUND)
  MESSAGE(STATUS "Found clang standard library in ${CLANG_STD_INCLUDE_DIR}")
ELSE(CLANG_STD_FOUND)
  IF(CLANG_STD_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find the clang standard library")
  ENDIF(CLANG_STD_FIND_REQUIRED)
ENDIF(CLANG_STD_FOUND)

MARK_AS_ADVANCED(
  CLANG_STD_INCLUDE_DIR
)

